name: isyaratku
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  loading_animation_widget: ^1.3.0
  camera: ^0.10.0+4
  image_picker: ^0.8.6+1
  google_ml_kit: ^0.20.0
  image: ^4.0.17

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_apk_isyaratku.png"
  min_sdk_android: 21 # minimum Android SDK min_sdk_android for Android. Default: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/alfabet/
    - assets/images/angka/
    - assets/icons/
